export const oldIngredients = [
    { name: 'Apple', quantity: null, id: '1' },
    { name: 'Banana', quantity: null, id: '2' },
    { name: 'Carrot', quantity: null, id: '3' },
    { name: 'Spinach', quantity: null, id: '4' },
    { name: 'Chicken Breast', quantity: null, id: '5' },
    { name: 'Ground Beef', quantity: null, id: '6' },
    { name: 'Tofu', quantity: null, id: '7' },
    { name: 'Eggs', quantity: null, id: '8' },
    { name: 'Cheddar Cheese', quantity: null, id: '9' },
    { name: 'Tomato', quantity: null, id: '10' },
    { name: 'Lettuce', quantity: null, id: '11' },
    { name: 'Potato', quantity: null, id: '12' },
    { name: 'Onion', quantity: null, id: '13' },
    { name: 'Garlic', quantity: null, id: '14' },
    { name: 'Olive Oil', quantity: null, id: '15' },
    { name: 'Salt', quantity: null, id: '16' },
    { name: 'Pepper', quantity: null, id: '17' },
    { name: 'Cinnamon', quantity: null, id: '18' },
    { name: 'Ginger', quantity: null, id: '19' },
    { name: 'Basil', quantity: null, id: '20' },
    { name: 'Oregano', quantity: null, id: '21' },
    { name: 'Milk', quantity: null, id: '22' },
    { name: 'Flour', quantity: null, id: '23' },
    { name: 'Sugar', quantity: null, id: '24' },
    { name: 'Butter', quantity: null, id: '25' },
    { name: 'Honey', quantity: null, id: '26' },
    { name: 'Lemon', quantity: null, id: '27' },
    { name: 'Lime', quantity: null, id: '28' },
    { name: 'Rice', quantity: null, id: '29' },
    { name: 'Pasta', quantity: null, id: '30' },
    { name: 'Soy Sauce', quantity: null, id: '31' },
    { name: 'Sesame Oil', quantity: null, id: '32' },
    { name: 'Cheese', quantity: null, id: '33' },
    { name: 'Avocado', quantity: null, id: '34' },
    { name: 'Cucumber', quantity: null, id: '35' },
    { name: 'Broccoli', quantity: null, id: '36' },
    { name: 'Mushrooms', quantity: null, id: '37' },
    { name: 'Peas', quantity: null, id: '38' },
    { name: 'Corn', quantity: null, id: '39' },
    { name: 'Zucchini', quantity: null, id: '40' },
    { name: 'Bell Pepper', quantity: null, id: '41' },
    { name: 'Squash', quantity: null, id: '42' },
    { name: 'Chili Powder', quantity: null, id: '43' },
    { name: 'Paprika', quantity: null, id: '44' },
    { name: 'Turmeric', quantity: null, id: '45' },
    { name: 'Parsley', quantity: null, id: '46' },
    { name: 'Cilantro', quantity: null, id: '47' },
    { name: 'Chives', quantity: null, id: '48' },
    { name: 'Thyme', quantity: null, id: '49' },
    { name: 'Rosemary', quantity: null, id: '50' },
    { name: 'Mint', quantity: null, id: '51' },
    { name: 'Feta Cheese', quantity: null, id: '52' },
    { name: 'Ricotta Cheese', quantity: null, id: '53' },
    { name: 'Cream Cheese', quantity: null, id: '54' },
    { name: 'Gouda Cheese', quantity: null, id: '55' },
    { name: 'Pineapple', quantity: null, id: '56' },
    { name: 'Watermelon', quantity: null, id: '57' },
    { name: 'Strawberry', quantity: null, id: '58' },
    { name: 'Blueberry', quantity: null, id: '59' },
    { name: 'Raspberries', quantity: null, id: '60' },
    { name: 'Grapes', quantity: null, id: '61' },
    { name: 'Peach', quantity: null, id: '62' },
    { name: 'Plum', quantity: null, id: '63' },
    { name: 'Cherries', quantity: null, id: '64' },
    { name: 'Coconut Milk', quantity: null, id: '65' },
    { name: 'Almond Milk', quantity: null, id: '66' },
    { name: 'Coconut Oil', quantity: null, id: '67' },
    { name: 'Almond Butter', quantity: null, id: '68' },
    { name: 'Peanut Butter', quantity: null, id: '69' },
    { name: 'Cashews', quantity: null, id: '70' },
    { name: 'Walnuts', quantity: null, id: '71' },
    { name: 'Pecans', quantity: null, id: '72' },
    { name: 'Sunflower Seeds', quantity: null, id: '73' },
    { name: 'Pumpkin Seeds', quantity: null, id: '74' },
    { name: 'Chia Seeds', quantity: null, id: '75' },
    { name: 'Flax Seeds', quantity: null, id: '76' },
    { name: 'Almonds', quantity: null, id: '77' },
    { name: 'Brazil Nuts', quantity: null, id: '78' },
    { name: 'Hazelnuts', quantity: null, id: '79' },
    { name: 'Macadamia Nuts', quantity: null, id: '80' },
    { name: 'Apricot', quantity: null, id: '81' },
    { name: 'Plum', quantity: null, id: '82' },
    { name: 'Papaya', quantity: null, id: '83' },
    { name: 'Mango', quantity: null, id: '84' },
    { name: 'Kiwi', quantity: null, id: '85' },
    { name: 'Dragon Fruit', quantity: null, id: '86' },
    { name: 'Pomegranate', quantity: null, id: '87' },
    { name: 'Figs', quantity: null, id: '88' },
    { name: 'Lychee', quantity: null, id: '89' },
    { name: 'Tamarind', quantity: null, id: '90' },
    { name: 'Aubergine', quantity: null, id: '91' },
    { name: 'Artichoke', quantity: null, id: '92' },
    { name: 'Leek', quantity: null, id: '93' },
    { name: 'Chard', quantity: null, id: '94' },
    { name: 'Kale', quantity: null, id: '95' },
    { name: 'Collard Greens', quantity: null, id: '96' },
    { name: 'Mustard Greens', quantity: null, id: '97' },
    { name: 'Turnip Greens', quantity: null, id: '98' },
    { name: 'Cabbage', quantity: null, id: '99' },
    { name: 'Brussels Sprouts', quantity: null, id: '100' },
  ];
  